import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    "antd",
    "rc-input",
    "rc-util",
    "@ant-design/icons",
    "@ant-design/icons-svg",
    "rc-pagination",
    "rc-picker",
    "rc-motion",
    "rc-field-form",
    "rc-notification",
    "rc-menu",
    "rc-tooltip",
    "rc-trigger",
    "rc-select",
    "rc-table",
    "rc-tree",
    "rc-checkbox",
    "rc-radio",
    "rc-switch",
    "rc-collapse",
    "rc-drawer",
    "rc-tabs",
    "rc-progress",
    "rc-slider",
    "rc-rate",
    "rc-upload",
    "rc-mentions",
    "rc-cascader",
    "rc-calendar",
    "rc-time-picker",
    "rc-color-picker",
    "rc-steps",
    "rc-timeline",
    "rc-animate",
    "rc-align",
    "rc-resize-observer",
    "rc-overflow",
    "rc-virtual-list",
    "rc-motion",
    "rc-image",
    "rc-dropdown",
    "rc-menu",
    "rc-tooltip",
    "rc-trigger",
    "rc-select",
    "rc-table",
    "rc-tree",
    "rc-checkbox",
    "rc-radio",
    "rc-switch",
    "rc-collapse",
    "rc-drawer",
    "rc-tabs",
    "rc-progress",
    "rc-slider",
    "rc-rate",
    "rc-upload",
    "rc-mentions",
    "rc-cascader",
    "rc-calendar",
    "rc-time-picker",
    "rc-color-picker",
    "rc-steps",
    "rc-timeline",
    "rc-animate",
    "rc-align",
    "rc-resize-observer",
    "rc-overflow",
    "rc-virtual-list",
    "rc-motion",
    "rc-image",
    "rc-dropdown",
  ],
  images: {
    domains: ["via.placeholder.com", "localhost"],
  },
  webpack: (config) => {
    config.resolve.fallback = { fs: false, path: false };
    return config;
  },
};

export default nextConfig;
